import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layout/nav/nav";
import Footer from "@/components/layout/footer";
import Disclaimer from "@/components/layout/disclaimer";
import { ReactQueryClientProvider } from "@/components/layout/QueryProvider";
import { ThemeProvider } from "@/components/layout/theme-provider";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`min-h-screen ${montserrat.className}`}>
        <ReactQueryClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Disclaimer />
            <div className="flex min-h-screen flex-col">
              <Nav />
              {children}
              <Footer />
            </div>
          </ThemeProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
